# Generated by Django 5.2.4 on 2025-09-19 03:22

from django.db import migrations, models


def extract_fields_data(apps, schema_editor):
    Person = apps.get_model('people', 'Person')

    for p in Person.objects.all():
        data = p.fullname + ';' + p.information
        data = dict(item.split(":", 1) for item in data.split(";"))
        data['birth_year'] = int(data['birth_year'])

        p.first_name = data['first_name']
        p.last_name = data['last_name']
        p.id_code = data['id_code']
        p.born_in = data['born_in']
        p.birth_year = data['birth_year']

        p.save()



class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='born_in',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='id_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),

        migrations.RunPython(extract_fields_data),

        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='born_in',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50),
        ),

        migrations.RemoveField(
            model_name='person',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='information',
        ),
    ]
